name: Get Sentiment and update GitHub page

on:
#   [push]
  schedule:
    - cron: "*/60 * * * *" # runs every 60 min
    
jobs:
  refresh_page:
    runs-on: ubuntu-latest    
    steps:
      - name: Access the repo
        uses: actions/checkout@v2 
    
      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' 
      
      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute python script to update sentiment page
        run: python update_index_ret.py
        
      - name: Clone repo from your github.io page and commit newly generated sentiment html file
        run: | #change all the "damianboh"s below to your username
          git clone https://github.com/chenpnn/chenpnn.github.io.git
          cp _includes/index_ret.html chenpnn.github.io/_includes/index_ret.html
          cd chenpnn.github.io/_includes
          git add index_ret.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'refresh page'        
        
      - name: Push updated html to github.io page
        uses: ad-m/github-push-action@master
        with: #change all the "damianboh"s below to your username
          github_token: ${{ secrets.TOKEN }}          
          repository: "chenpnn/chenpnn.github.io"
          branch: "main"          
          directory: ./chenpnn.github.io
